// Code generated by mockery v2.39.2. DO NOT EDIT.

package mocks

import (
	entity "library/entity"

	mock "github.com/stretchr/testify/mock"
)

// MailInterface is an autogenerated mock type for the MailInterface type
type MailInterface struct {
	mock.Mock
}

// Send provides a mock function with given fields: header
func (_m *MailInterface) Send(header entity.Mail) error {
	ret := _m.Called(header)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Mail) error); ok {
		r0 = rf(header)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailInterface creates a new instance of MailInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailInterface {
	mock := &MailInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
