// Code generated by mockery v2.39.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "library/entity"

	mock "github.com/stretchr/testify/mock"
)

// XenditInterface is an autogenerated mock type for the XenditInterface type
type XenditInterface struct {
	mock.Mock
}

// CheckPayment provides a mock function with given fields: ctx, payment
func (_m *XenditInterface) CheckPayment(ctx context.Context, payment entity.XenditPaymentResponse) (entity.XenditPaymentResponse, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CheckPayment")
	}

	var r0 entity.XenditPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.XenditPaymentResponse) (entity.XenditPaymentResponse, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.XenditPaymentResponse) entity.XenditPaymentResponse); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(entity.XenditPaymentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.XenditPaymentResponse) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePayment provides a mock function with given fields: ctx, payment
func (_m *XenditInterface) CreatePayment(ctx context.Context, payment entity.XenditPaymentRequest) (entity.XenditPaymentResponse, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 entity.XenditPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.XenditPaymentRequest) (entity.XenditPaymentResponse, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.XenditPaymentRequest) entity.XenditPaymentResponse); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(entity.XenditPaymentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.XenditPaymentRequest) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewXenditInterface creates a new instance of XenditInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewXenditInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *XenditInterface {
	mock := &XenditInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
